"""rename_keywords_to_keyword

Revision ID: df4b745c4a89
Revises: 90bc1b464159
Create Date: 2026-04-29 18:04:45.403858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df4b745c4a89'
down_revision: Union[str, Sequence[str], None] = '90bc1b464159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('keyword', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('products', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'keyword')
    # ### end Alembic commands ###
